"""empty message

Revision ID: 1491687b9b3a
Revises: b0cd8ad6d3f9
Create Date: 2024-04-28 19:03:28.695818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1491687b9b3a'
down_revision: Union[str, None] = 'b0cd8ad6d3f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phono_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('brief_summary', sa.String(length=500), nullable=False),
    sa.Column('addressee', sa.String(length=500), nullable=False),
    sa.Column('cypher', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=255), nullable=False),
    sa.Column('storage_media', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phono_documents_id'), 'phono_documents', ['id'], unique=False)
    op.create_table('search_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cypher', sa.String(length=255), nullable=False),
    sa.Column('fund', sa.String(length=255), nullable=False),
    sa.Column('inventory', sa.String(length=255), nullable=False),
    sa.Column('case', sa.String(length=255), nullable=False),
    sa.Column('leaf', sa.String(length=255), nullable=False),
    sa.Column('authenticity', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=255), nullable=False),
    sa.Column('playback_method', sa.String(length=500), nullable=False),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_data_id'), 'search_data', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('search_data_id', sa.BigInteger(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('variety', sa.String(length=255), nullable=False),
    sa.Column('addressee', sa.String(length=500), nullable=False),
    sa.Column('brief_content', sa.Text(), nullable=False),
    sa.Column('case_prod_number', sa.String(length=255), nullable=False),
    sa.Column('main_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_data_id'], ['search_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('photo_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('search_data_id', sa.BigInteger(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('completeness_of_reproduction', sa.String(length=500), nullable=False),
    sa.Column('storage_media', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('size_of_original', sa.String(length=255), nullable=False),
    sa.Column('image_scale', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_data_id'], ['search_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_documents_id'), 'photo_documents', ['id'], unique=False)
    op.create_table('video_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('search_data_id', sa.BigInteger(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('volume', sa.String(length=255), nullable=False),
    sa.Column('num_of_parts', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('creator', sa.String(length=500), nullable=False),
    sa.Column('info_of_publication', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_data_id'], ['search_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_documents_id'), 'video_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_documents_id'), table_name='video_documents')
    op.drop_table('video_documents')
    op.drop_index(op.f('ix_photo_documents_id'), table_name='photo_documents')
    op.drop_table('photo_documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_search_data_id'), table_name='search_data')
    op.drop_table('search_data')
    op.drop_index(op.f('ix_phono_documents_id'), table_name='phono_documents')
    op.drop_table('phono_documents')
    # ### end Alembic commands ###
