"""empty message

Revision ID: 1f2d0fb6bed9
Revises: 1491687b9b3a
Create Date: 2024-05-18 17:16:48.422892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f2d0fb6bed9'
down_revision: Union[str, None] = '1491687b9b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('documents_search_data_id_fkey', 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'search_data', ['search_data_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('photo_documents_search_data_id_fkey', 'photo_documents', type_='foreignkey')
    op.create_foreign_key(None, 'photo_documents', 'search_data', ['search_data_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('video_documents_search_data_id_fkey', 'video_documents', type_='foreignkey')
    op.create_foreign_key(None, 'video_documents', 'search_data', ['search_data_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'video_documents', type_='foreignkey')
    op.create_foreign_key('video_documents_search_data_id_fkey', 'video_documents', 'search_data', ['search_data_id'], ['id'])
    op.drop_constraint(None, 'photo_documents', type_='foreignkey')
    op.create_foreign_key('photo_documents_search_data_id_fkey', 'photo_documents', 'search_data', ['search_data_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key('documents_search_data_id_fkey', 'documents', 'search_data', ['search_data_id'], ['id'])
    # ### end Alembic commands ###
