"""empty message

Revision ID: 647db2103af8
Revises: e2cdcf7b3888
Create Date: 2024-09-19 21:30:17.607515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '647db2103af8'
down_revision: Union[str, None] = 'e2cdcf7b3888'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_collection', sa.Column('is_seen', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uix_collection_user', 'notification_collection', ['collection_id', 'user_id'])
    op.drop_column('notification_collection', 'text')
    op.create_unique_constraint('uix_collection_redactor', 'redactor_group', ['collection_id', 'redactor_id'])
    op.add_column('scientific_council_group', sa.Column('is_approved', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uix_collection_scientific_council', 'scientific_council_group', ['collection_id', 'scientific_council_id'])
    op.drop_column('scientific_council_group', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scientific_council_group', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint('uix_collection_scientific_council', 'scientific_council_group', type_='unique')
    op.drop_column('scientific_council_group', 'is_approved')
    op.drop_constraint('uix_collection_redactor', 'redactor_group', type_='unique')
    op.add_column('notification_collection', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('uix_collection_user', 'notification_collection', type_='unique')
    op.drop_column('notification_collection', 'is_seen')
    # ### end Alembic commands ###
