"""empty message

Revision ID: 72803faa1739
Revises: 647db2103af8
Create Date: 2024-09-25 11:49:14.739712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72803faa1739'
down_revision: Union[str, None] = '647db2103af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_collection_user', 'notification_collection', type_='unique')
    op.drop_column('redactor_group', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('redactor_group', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_unique_constraint('uix_collection_user', 'notification_collection', ['collection_id', 'user_id'])
    # ### end Alembic commands ###
