"""empty message

Revision ID: 729a16289530
Revises: 
Create Date: 2024-08-20 21:37:23.108179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '729a16289530'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phono_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_urls', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('brief_summary', sa.String(length=500), nullable=False),
    sa.Column('addressee', sa.String(length=500), nullable=False),
    sa.Column('cypher', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=255), nullable=False),
    sa.Column('storage_media', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phono_documents_id'), 'phono_documents', ['id'], unique=True)
    op.create_table('search_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cypher', sa.String(length=255), nullable=False),
    sa.Column('fund', sa.String(length=255), nullable=False),
    sa.Column('inventory', sa.String(length=255), nullable=False),
    sa.Column('case', sa.String(length=255), nullable=False),
    sa.Column('leaf', sa.String(length=255), nullable=False),
    sa.Column('authenticity', sa.String(length=255), nullable=False),
    sa.Column('lang', sa.String(length=255), nullable=False),
    sa.Column('playback_method', sa.String(length=500), nullable=False),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_data_id'), 'search_data', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('firstname', sa.String(length=250), nullable=False),
    sa.Column('lastname', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('role', sa.Enum('BasicUser', 'AdminUser', 'RedactorUser', 'ScientificCouncil', name='role'), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('collection',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('html_url', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=700), nullable=False),
    sa.Column('title', sa.String(length=700), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('hash_code', sa.String(length=7), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_code')
    )
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_data_id', sa.BigInteger(), nullable=False),
    sa.Column('file_urls', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('variety', sa.String(length=255), nullable=False),
    sa.Column('addressee', sa.String(length=500), nullable=False),
    sa.Column('brief_content', sa.Text(), nullable=False),
    sa.Column('case_prod_number', sa.String(length=255), nullable=False),
    sa.Column('main_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_data_id'], ['search_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=True)
    op.create_table('photo_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_data_id', sa.BigInteger(), nullable=False),
    sa.Column('file_urls', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('completeness_of_reproduction', sa.String(length=500), nullable=False),
    sa.Column('storage_media', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('size_of_original', sa.String(length=255), nullable=False),
    sa.Column('image_scale', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_data_id'], ['search_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_documents_id'), 'photo_documents', ['id'], unique=True)
    op.create_table('video_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('search_data_id', sa.BigInteger(), nullable=False),
    sa.Column('file_urls', sa.JSON(), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('place_of_creating', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('volume', sa.String(length=255), nullable=False),
    sa.Column('num_of_parts', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=255), nullable=False),
    sa.Column('creator', sa.String(length=500), nullable=False),
    sa.Column('info_of_publication', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_data_id'], ['search_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_documents_id'), 'video_documents', ['id'], unique=True)
    op.create_table('document_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_links_id'), 'document_links', ['id'], unique=False)
    op.create_table('notification_collection',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_collection_id'), 'notification_collection', ['id'], unique=False)
    op.create_table('phono_document_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('phono_document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phono_document_id'], ['phono_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phono_document_links_id'), 'phono_document_links', ['id'], unique=False)
    op.create_table('photo_document_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('photo_document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_document_id'], ['photo_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_document_links_id'), 'photo_document_links', ['id'], unique=False)
    op.create_table('redactor_group',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('redactor_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['redactor_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_redactor_group_id'), 'redactor_group', ['id'], unique=False)
    op.create_table('scientific_council_group',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('scientific_council_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scientific_council_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scientific_council_group_id'), 'scientific_council_group', ['id'], unique=False)
    op.create_table('video_document_links',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('collection_id', sa.UUID(), nullable=False),
    sa.Column('video_document_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_document_id'], ['video_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_video_document_links_id'), 'video_document_links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_document_links_id'), table_name='video_document_links')
    op.drop_table('video_document_links')
    op.drop_index(op.f('ix_scientific_council_group_id'), table_name='scientific_council_group')
    op.drop_table('scientific_council_group')
    op.drop_index(op.f('ix_redactor_group_id'), table_name='redactor_group')
    op.drop_table('redactor_group')
    op.drop_index(op.f('ix_photo_document_links_id'), table_name='photo_document_links')
    op.drop_table('photo_document_links')
    op.drop_index(op.f('ix_phono_document_links_id'), table_name='phono_document_links')
    op.drop_table('phono_document_links')
    op.drop_index(op.f('ix_notification_collection_id'), table_name='notification_collection')
    op.drop_table('notification_collection')
    op.drop_index(op.f('ix_document_links_id'), table_name='document_links')
    op.drop_table('document_links')
    op.drop_index(op.f('ix_video_documents_id'), table_name='video_documents')
    op.drop_table('video_documents')
    op.drop_index(op.f('ix_photo_documents_id'), table_name='photo_documents')
    op.drop_table('photo_documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_search_data_id'), table_name='search_data')
    op.drop_table('search_data')
    op.drop_index(op.f('ix_phono_documents_id'), table_name='phono_documents')
    op.drop_table('phono_documents')
    # ### end Alembic commands ###
