"""empty message

Revision ID: 73eca2721cce
Revises: 
Create Date: 2024-03-16 18:42:47.613539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73eca2721cce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_coll',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_class_coll_id'), 'class_coll', ['id'], unique=False)
    op.create_table('format_coll',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_format_coll_id'), 'format_coll', ['id'], unique=False)
    op.create_table('method_coll',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_method_coll_id'), 'method_coll', ['id'], unique=False)
    op.create_table('type_coll',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_type_coll_id'), 'type_coll', ['id'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('theme', sa.String(length=700), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('task', sa.String(length=1000), nullable=False),
    sa.Column('type_id', sa.BigInteger(), nullable=False),
    sa.Column('class_id', sa.BigInteger(), nullable=False),
    sa.Column('format_id', sa.BigInteger(), nullable=False),
    sa.Column('method_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('preface', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('indication', sa.Text(), nullable=True),
    sa.Column('intro_text', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['class_coll.id'], ),
    sa.ForeignKeyConstraint(['format_id'], ['format_coll.id'], ),
    sa.ForeignKeyConstraint(['method_id'], ['method_coll.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type_coll.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_id'), 'collection', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_type_coll_id'), table_name='type_coll')
    op.drop_table('type_coll')
    op.drop_index(op.f('ix_method_coll_id'), table_name='method_coll')
    op.drop_table('method_coll')
    op.drop_index(op.f('ix_format_coll_id'), table_name='format_coll')
    op.drop_table('format_coll')
    op.drop_index(op.f('ix_class_coll_id'), table_name='class_coll')
    op.drop_table('class_coll')
    # ### end Alembic commands ###
