"""empty message

Revision ID: 77ee5980b5a7
Revises: 73eca2721cce
Create Date: 2024-03-18 14:20:10.691196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ee5980b5a7'
down_revision: Union[str, None] = '73eca2721cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=700), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=500), nullable=False),
    sa.Column('description_content', sa.String(length=1000), nullable=False),
    sa.Column('dating', sa.String(length=255), nullable=False),
    sa.Column('legends', sa.Text(), nullable=False),
    sa.Column('format_doc', sa.String(length=500), nullable=False),
    sa.Column('color_palette', sa.String(length=500), nullable=False),
    sa.Column('resolution', sa.String(length=500), nullable=False),
    sa.Column('compression', sa.String(length=500), nullable=False),
    sa.Column('scanner_model', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
