"""empty message

Revision ID: 847e0eae66aa
Revises: 1f2d0fb6bed9
Create Date: 2024-05-30 17:30:44.791102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847e0eae66aa'
down_revision: Union[str, None] = '1f2d0fb6bed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_urls', sa.JSON(), nullable=False))
    op.drop_column('documents', 'file_url')
    op.add_column('phono_documents', sa.Column('file_urls', sa.JSON(), nullable=False))
    op.drop_column('phono_documents', 'file_url')
    op.add_column('photo_documents', sa.Column('file_urls', sa.JSON(), nullable=False))
    op.drop_column('photo_documents', 'file_url')
    op.add_column('video_documents', sa.Column('file_urls', sa.JSON(), nullable=False))
    op.drop_column('video_documents', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_documents', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('video_documents', 'file_urls')
    op.add_column('photo_documents', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('photo_documents', 'file_urls')
    op.add_column('phono_documents', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('phono_documents', 'file_urls')
    op.add_column('documents', sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('documents', 'file_urls')
    # ### end Alembic commands ###
