"""empty message

Revision ID: ea874e21a6fa
Revises: d2a77511c9a8
Create Date: 2024-11-19 12:10:06.737728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea874e21a6fa'
down_revision: Union[str, None] = 'd2a77511c9a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_collection_comment', 'collection_comment', ['collection_id', 'user_id'])
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('BasicUser', 'AdminUser', 'RedactorUser', 'ScientificCouncil', name='role'),
               type_=sa.String(length=250),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=sa.String(length=250),
               type_=postgresql.ENUM('BasicUser', 'AdminUser', 'RedactorUser', 'ScientificCouncil', name='role'),
               existing_nullable=False)
    op.drop_constraint('uix_collection_comment', 'collection_comment', type_='unique')
    # ### end Alembic commands ###
