"""empty message

Revision ID: eca7eb6e8f4a
Revises: abdf852c7f2f
Create Date: 2025-03-10 08:13:06.941147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eca7eb6e8f4a'
down_revision: Union[str, None] = 'abdf852c7f2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection', sa.Column('isbn_link', sa.String(length=255), nullable=True))
    op.add_column('collection', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection', 'description')
    op.drop_column('collection', 'isbn_link')
    # ### end Alembic commands ###
