"""empty message

Revision ID: f0f9b3b5742b
Revises: 
Create Date: 2024-03-11 12:27:00.626093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0f9b3b5742b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_class_id'), 'class', ['id'], unique=False)
    op.create_table('form',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_form_id'), 'form', ['id'], unique=False)
    op.create_table('method',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_method_id'), 'method', ['id'], unique=False)
    op.create_table('type',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id', 'name'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_type_id'), 'type', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_id'), table_name='type')
    op.drop_table('type')
    op.drop_index(op.f('ix_method_id'), table_name='method')
    op.drop_table('method')
    op.drop_index(op.f('ix_form_id'), table_name='form')
    op.drop_table('form')
    op.drop_index(op.f('ix_class_id'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
